export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const SEARCH_GAMES = "SEARCH_GAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEGAME_DETAIL";
export const GET_GENRES = "GET_GENRES";
export const GET_PLATFORMS = "GET_PLATFORMS"
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const CLEAR_PAGE = "CLEAR_PAGE";
export const FILTER = "FILTER";
